CREATE DATABASE CAR_STAT default CHARACTER SET UTF8;
 
use CAT_STAT;
 
CREATE TABLE testTable(
    idx      INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    test     VARCHAR(256) NOT NULL
) CHARSET=utf8;

